-- ================================
-- CONSULTA AULAS UPDS - SUPABASE
-- ================================

-- 1) TABLA PRINCIPAL
create table if not exists asignaciones (
  id bigint generated by default as identity primary key,
  turno text not null,
  materia text not null,
  docente text not null,
  aula text not null,
  horario text not null,
  docente_norm text not null,
  materia_norm text not null,
  aula_norm text not null,
  horario_norm text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2) AUDIT LOG
create table if not exists auditlog (
  id bigint generated by default as identity primary key,
  action text not null,
  record_id bigint null,
  user_agent text,
  client_id text,
  old_value jsonb,
  new_value jsonb,
  extra jsonb,
  created_at timestamptz default now()
);

-- 3) SESIONES ACTIVAS (solo advertencia)
create table if not exists admin_sessions (
  client_id text primary key,
  user_agent text,
  created_at timestamptz default now(),
  last_seen timestamptz default now()
);

-- ================================
-- INDICES
-- ================================
create index if not exists idx_asignaciones_docente_norm on asignaciones (docente_norm);
create index if not exists idx_asignaciones_materia_norm on asignaciones (materia_norm);
create index if not exists idx_asignaciones_aula_norm on asignaciones (aula_norm);
create index if not exists idx_asignaciones_turno on asignaciones (turno);

create index if not exists idx_auditlog_action on auditlog (action);
create index if not exists idx_auditlog_created_at on auditlog (created_at);

create index if not exists idx_admin_sessions_last_seen on admin_sessions (last_seen);

-- ================================
-- RLS (DESACTIVADO)
-- ================================
alter table asignaciones disable row level security;
alter table auditlog disable row level security;
alter table admin_sessions disable row level security;

-- ================================
-- POLÍTICAS OPCIONALES (si algún día activas RLS)
-- ================================
-- Para habilitar luego:
-- alter table asignaciones enable row level security;
-- alter table auditlog enable row level security;
-- alter table admin_sessions enable row level security;

-- Lectura pública de asignaciones (estudiantes)
-- create policy "public_read_asignaciones"
-- on asignaciones for select
-- to anon
-- using (true);

-- Escritura libre (solo si deseas permitir CRUD sin auth)
-- create policy "public_write_asignaciones"
-- on asignaciones for insert
-- to anon
-- with check (true);

-- create policy "public_update_asignaciones"
-- on asignaciones for update
-- to anon
-- using (true);

-- create policy "public_delete_asignaciones"
-- on asignaciones for delete
-- to anon
-- using (true);

-- Auditlog solo insert
-- create policy "public_insert_auditlog"
-- on auditlog for insert
-- to anon
-- with check (true);

-- Sesiones activas
-- create policy "public_read_sessions"
-- on admin_sessions for select
-- to anon
-- using (true);

-- create policy "public_upsert_sessions"
-- on admin_sessions for insert
-- to anon
-- with check (true);

-- create policy "public_update_sessions"
-- on admin_sessions for update
-- to anon
-- using (true);
